package vm

import (
	"context"
	"encoding/json"
	"fmt"
	"net"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

const bridgeNetworkName = "macbox-bridged"
const bridgeBinary = "/opt/socket_vmnet/bin/socket_vmnet"

type NetworkStatus struct {
	Mode      string `json:"mode"`
	Interface string `json:"interface"`
	IP        string `json:"ip"`
	Ready     bool   `json:"ready"`
	Installed bool   `json:"installed"`
	Message   string `json:"message"`
}

var physicalInterface = regexp.MustCompile(`^en[0-9]+$`)

func bridgeHostInterface(ctx context.Context) (string, error) {
	out, err := exec.CommandContext(ctx, "/sbin/route", "-n", "get", "default").Output()
	if err == nil {
		for _, line := range strings.Split(string(out), "\n") {
			fields := strings.Fields(line)
			if len(fields) == 2 && fields[0] == "interface:" && physicalInterface.MatchString(fields[1]) {
				return fields[1], nil
			}
		}
	}
	// VPN default routes point to utun. Use an active physical adapter rather
	// than accidentally bridging the tunnel or hard-coding Wi-Fi's en0.
	interfaces, err := net.Interfaces()
	if err != nil {
		return "", err
	}
	for _, iface := range interfaces {
		if !physicalInterface.MatchString(iface.Name) || iface.Flags&net.FlagUp == 0 {
			continue
		}
		addresses, _ := iface.Addrs()
		for _, address := range addresses {
			ip, _, e := net.ParseCIDR(address.String())
			if e == nil && ip.To4() != nil && !ip.IsLoopback() && !ip.IsLinkLocalUnicast() {
				return iface.Name, nil
			}
		}
	}
	return "", fmt.Errorf("未找到已连接的以太网或 Wi-Fi，请先连接局域网")
}

// Configure only our named network; preserve other Lima networks and custom
// paths. Lima's generated sudoers must match these exact adapter arguments.
func configureBridgeNetwork(home, adapter string) error {
	if !physicalInterface.MatchString(adapter) {
		return fmt.Errorf("无效的桥接网卡")
	}
	path := filepath.Join(home, ".lima", "_config", "networks.yaml")
	doc := map[string]interface{}{}
	if data, err := os.ReadFile(path); err == nil {
		if err := yaml.Unmarshal(data, &doc); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	paths, _ := doc["paths"].(map[string]interface{})
	if paths == nil {
		paths = map[string]interface{}{}
	}
	paths["socketVMNet"] = bridgeBinary
	paths["varRun"] = "/private/var/run/lima"
	paths["sudoers"] = "/private/etc/sudoers.d/lima"
	doc["paths"] = paths
	if _, ok := doc["group"]; !ok {
		doc["group"] = "admin"
	}
	networks, _ := doc["networks"].(map[string]interface{})
	if networks == nil {
		networks = map[string]interface{}{}
	}
	networks[bridgeNetworkName] = map[string]interface{}{"mode": "bridged", "interface": adapter}
	doc["networks"] = networks
	data, err := yaml.Marshal(doc)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	if previous, err := os.ReadFile(path); err == nil && string(previous) == string(data) {
		return nil
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".networks-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err = tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err = tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}

func (m *Manager) EnsureBridge(ctx context.Context) error {
	if runtime.GOOS != "darwin" {
		return fmt.Errorf("自动桥接仅支持 macOS")
	}
	adapter, err := bridgeHostInterface(ctx)
	if err != nil {
		return err
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	if err := configureBridgeNetwork(home, adapter); err != nil {
		return fmt.Errorf("配置桥接网络失败: %w", err)
	}
	if _, err := os.Stat(bridgeBinary); err == nil {
		if err := exec.CommandContext(ctx, limaCommandPath(), "sudoers", "--check").Run(); err == nil {
			return nil
		}
	}
	brew, ok := FindHomebrew()
	if !ok {
		return fmt.Errorf("请先安装 Homebrew，以安装自动桥接组件")
	}
	brewPrefix, err := exec.CommandContext(ctx, brew, "--prefix").Output()
	if err != nil {
		return err
	}
	source := filepath.Join(strings.TrimSpace(string(brewPrefix)), "opt", "socket_vmnet", "bin", "socket_vmnet")
	if _, err := os.Stat(source); os.IsNotExist(err) {
		if out, err := runHostCommand(ctx, brew, "install", "socket_vmnet"); err != nil {
			return fmt.Errorf("安装桥接组件失败: %s (%w)", out, err)
		}
	}
	account, err := user.Current()
	if err != nil {
		return err
	}
	// The native macOS authentication prompt is shown once for the root-owned
	// bridge binary and the least-privilege rules generated by Lima itself.
	command := "set -eu; for p in /opt /opt/socket_vmnet /opt/socket_vmnet/bin /private/etc/sudoers.d; do [ ! -L \"$p\" ] || exit 1; done; " +
		"/usr/bin/install -d -o root -g wheel -m 0755 /opt/socket_vmnet /opt/socket_vmnet/bin; " +
		"/usr/bin/install -o root -g wheel -m 0755 " + shellQuote(source) + " " + bridgeBinary + "; " +
		"t=$(/usr/bin/mktemp /private/tmp/macbox-sudoers.XXXXXX); trap '/bin/rm -f \"$t\"' EXIT; " +
		"/usr/bin/sudo -H -u " + shellQuote(account.Username) + " " + shellQuote(limaCommandPath()) + " sudoers > \"$t\"; " +
		"/usr/sbin/visudo -cf \"$t\"; /usr/bin/install -o root -g wheel -m 0644 \"$t\" /private/etc/sudoers.d/lima"
	script := "on run argv\n do shell script (item 1 of argv) with administrator privileges with prompt \"MacBox 需要安装局域网桥接组件，让虚拟机直接获得局域网 IP。\"\nend run"
	if out, err := runHostCommand(ctx, "/usr/bin/osascript", "-e", script, command); err != nil {
		return fmt.Errorf("桥接授权未完成: %s (%w)", strings.TrimSpace(out), err)
	}
	return nil
}

func (m *Manager) NetworkStatus(ctx context.Context) NetworkStatus {
	status := NetworkStatus{Mode: "bridged", Message: "网络尚未连接"}
	_, err := os.Stat(bridgeBinary)
	status.Installed = err == nil
	home, _ := os.UserHomeDir()
	data, err := os.ReadFile(filepath.Join(home, ".lima", "_config", "networks.yaml"))
	if err == nil {
		var doc struct {
			Networks map[string]struct {
				Interface string `yaml:"interface"`
			} `yaml:"networks"`
		}
		if yaml.Unmarshal(data, &doc) == nil {
			status.Interface = doc.Networks[bridgeNetworkName].Interface
		}
	}
	probeCtx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	out, err := m.Exec(probeCtx, "ip", "-j", "-4", "address", "show", "lima0")
	if err == nil {
		status.IP = parseBridgeIP(out)
	}
	status.Ready = status.IP != ""
	if status.Ready {
		status.Message = "已连接，其他设备可用系统地址访问"
	} else if !status.Installed {
		status.Message = "首次连接，请在Mac上完成管理员授权"
	} else {
		status.Message = "系统未运行，或仍在等待网络地址"
	}
	return status
}

func parseBridgeIP(raw string) string {
	var interfaces []struct {
		Name      string `json:"ifname"`
		Addresses []struct {
			Family string `json:"family"`
			Local  string `json:"local"`
			Scope  string `json:"scope"`
		} `json:"addr_info"`
	}
	if json.Unmarshal([]byte(raw), &interfaces) != nil {
		return ""
	}
	for _, iface := range interfaces {
		if iface.Name != "lima0" {
			continue
		}
		for _, address := range iface.Addresses {
			ip := net.ParseIP(address.Local)
			if address.Family == "inet" && address.Scope == "global" && ip != nil && ip.To4() != nil && !ip.IsLoopback() && !ip.IsLinkLocalUnicast() && address.Local != "192.168.5.15" {
				return address.Local
			}
		}
	}
	return ""
}
