import { useState } from 'react';
import { api } from '../../api';
import type { SystemOverview } from '../../types';

export function SettingsOverviewSection({ overview, isAdmin, onRefresh, onSelect, onNavigate }: { overview?: SystemOverview | null; isAdmin: boolean; onRefresh?: () => void; onSelect: (tab: 'network' | 'remote' | 'updates' | 'backup') => void; onNavigate?: (tab: 'storage_settings' | 'smb_sharing') => void }) {
  const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  async function toggle(kind: 'power' | 'service') {
    setBusy(kind); setError('');
    try { if (kind === 'power') await api.togglePower(!overview?.power?.preventSleep); else if (overview?.service?.installed) await api.uninstallService(); else await api.installService(); onRefresh?.(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); }
  }
  return <div className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900 p-5"><h3 className="font-semibold mb-4">运行状态</h3><div className="grid gap-4 sm:grid-cols-3 text-sm"><div><p className="text-xs text-slate-500">运行系统</p><p className="mt-1">{overview?.vm.status === 'Running' ? '运行中' : '未运行'}</p></div><div><p className="text-xs text-slate-500">系统地址</p><button onClick={() => onSelect('network')} className="mt-1 font-mono text-sky-500">{overview?.vm.bridgeIP || "连接设置"}</button></div><div><p className="text-xs text-slate-500">本机地址</p><p className="mt-1 font-mono">{overview?.system.primaryIP || "待检测"}</p></div></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900 p-5"><h3 className="font-semibold mb-2">日常使用</h3>{[{ id: 'power' as const, title: '保持运行', description: "关闭显示器后继续运行。\n合盖后是否运行由Mac系统决定。", enabled: overview?.power?.preventSleep }, { id: 'service' as const, title: "自动启动", description: "登录Mac后自动启动后台", enabled: overview?.service?.installed }].map(item => <div key={item.id} className="flex items-center justify-between gap-4 py-4 border-b last:border-0 border-slate-100 dark:border-slate-800"><div><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.description}</p></div><button role="switch" aria-checked={!!item.enabled} aria-label={item.title} disabled={!isAdmin || !!busy} onClick={() => toggle(item.id)} className={`shrink-0 w-11 h-6 rounded-full p-1 transition disabled:opacity-50 ${item.enabled ? 'bg-sky-500' : 'bg-slate-300 dark:bg-slate-700'}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${item.enabled ? 'translate-x-5' : ''}`}/></button></div>)}</section>
    <section className="grid gap-3 sm:grid-cols-2">{[{ title: "存储管理", detail: "查看磁盘和文件夹", action: () => onNavigate?.('storage_settings') }, { title: '文件共享', detail: "让其他设备访问指定文件夹", action: () => onNavigate?.('smb_sharing') }, { title: '版本更新', detail: "查看新版本和更新记录", action: () => onSelect('updates') }, ...(isAdmin ? [{ title: '远程访问', detail: '在外面访问应用和后台', action: () => onSelect('remote') }, { title: "备份恢复", detail: "备份账号和设置", action: () => onSelect('backup') }] : [])].map(item => <button key={item.title} onClick={item.action} className="text-left rounded-2xl border border-slate-200 bg-white p-4 dark:bg-slate-900 dark:border-slate-800 hover:border-sky-400 transition"><p className="text-sm font-medium">{item.title} →</p><p className="text-xs text-slate-500 mt-1">{item.detail}</p></button>)}</section>{error && <p role="alert" className="text-sm text-rose-500">{error}</p>}</div>;
}
