package config

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"net"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"unicode"

	"gopkg.in/yaml.v3"
)

type Config struct {
	Port          int           `yaml:"port"`
	ListenAddress string        `yaml:"listenAddress"`
	VM            VMConfig      `yaml:"vm"`
	Storage       StorageConfig `yaml:"storage"`
	Samba         SambaConfig   `yaml:"samba"`
	System        SystemConfig  `yaml:"system"`
}

type SystemConfig struct {
	PreventSleep bool `yaml:"preventSleep"` // 24h keep-awake with caffeinate
	AutoStart    bool `yaml:"autoStart"`    // macOS LaunchAgent autostart on boot
}

type VMConfig struct {
	Name           string `yaml:"name"`
	CPUs           int    `yaml:"cpus"`
	Memory         int    `yaml:"memory"`   // GiB
	DiskSize       int    `yaml:"diskSize"` // GiB rootfs
	DataDiskName   string `yaml:"dataDiskName"`
	ForwardedPorts []int  `yaml:"forwardedPorts"`
}

type LocalMount struct {
	ID          string `json:"id" yaml:"id"`
	Name        string `json:"name" yaml:"name"`
	HostPath    string `json:"hostPath" yaml:"hostPath"`
	GuestTarget string `json:"guestTarget" yaml:"guestTarget"` // Target directory under /data
	Writable    bool   `json:"writable" yaml:"writable"`       // Read-only by default
	Enabled     bool   `json:"enabled" yaml:"enabled"`
	Category    string `json:"category" yaml:"category"` // media, downloads, pictures, custom
	Description string `json:"description" yaml:"description"`
}

type StorageConfig struct {
	SelectedDisk   string       `yaml:"selectedDisk"`   // e.g. /dev/disk4 (Primary NAS Data Disk)
	MountPoint     string       `yaml:"mountPoint"`     // Host mount point if any
	DataPath       string       `yaml:"dataPath"`       // Host path holding data or managed disk
	SecondaryDisk  string       `yaml:"secondaryDisk"`  // e.g. disk0 (Secondary / High-Speed SSD Pool)
	SecondaryMount string       `yaml:"secondaryMount"` // Host path on secondary disk
	LocalMounts    []LocalMount `yaml:"localMounts"`    // VirtioFS direct folder mounts from Mac
}

type SMBShare struct {
	ID         string `json:"id" yaml:"id"`
	Name       string `json:"name" yaml:"name"`
	Path       string `json:"path" yaml:"path"`
	Comment    string `json:"comment" yaml:"comment"`
	Writable   bool   `json:"writable" yaml:"writable"`     // true = 读写, false = 只读
	GuestOk    bool   `json:"guestOk" yaml:"guestOk"`       // true = 允许访客免密
	Enabled    bool   `json:"enabled" yaml:"enabled"`       // true = 开启共享
	DiskSource string `json:"diskSource" yaml:"diskSource"` // "primary", "secondary", "passthrough", "custom"
}

type SambaConfig struct {
	ShareName string     `yaml:"shareName"`
	Port      int        `yaml:"port"`
	User      string     `yaml:"user"`
	Password  string     `yaml:"password"`
	Shares    []SMBShare `yaml:"shares"`
}

func DefaultConfig() *Config {
	return &Config{
		Port:          19808,
		ListenAddress: "127.0.0.1",
		VM: VMConfig{
			Name:         "macnas",
			CPUs:         2,
			Memory:       4,
			DiskSize:     20,
			DataDiskName: "macnas-data",
			// Only forward ports used by the built-in web applications. New
			// application ports are added explicitly during installation.
			ForwardedPorts: []int{5244, 8082, 8085},
		},
		Storage: StorageConfig{
			SelectedDisk: "",
			MountPoint:   "",
			DataPath:     "",
		},
		Samba: SambaConfig{
			ShareName: "MacNAS",
			Port:      4455, // default non-conflicting host port on macOS
			User:      "macnas",
			// Generated by LoadConfig/EnsureSecrets. Never ship a known
			// Samba password in the default configuration.
			Password: "",
		},
		System: SystemConfig{
			PreventSleep: true, // Default enabled for Mac mini NAS server
			AutoStart:    false,
		},
	}
}

// NormalizeForwardedPorts removes duplicates and rejects invalid TCP ports
// before they reach the Lima configuration template.
func NormalizeForwardedPorts(ports []int) []int {
	seen := make(map[int]struct{}, len(ports))
	clean := make([]int, 0, len(ports))
	for _, port := range ports {
		if port < 1 || port > 65535 {
			continue
		}
		if _, exists := seen[port]; exists {
			continue
		}
		seen[port] = struct{}{}
		clean = append(clean, port)
	}
	sort.Ints(clean)
	return clean
}

const legacySambaPassword = "macnas123"

const (
	minSambaPasswordBytes = 12
	maxSambaPasswordBytes = 256
)

var (
	dataDiskNamePattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$`)
	localMountIDPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$`)
	vmNamePattern       = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$`)
)

// NormalizeDataDiskName validates the name that is interpolated into both
// Lima YAML and guest mount paths. Disk names are identifiers, not paths.
func NormalizeDataDiskName(name string) (string, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return "macnas-data", nil
	}
	if !dataDiskNamePattern.MatchString(name) {
		return "", fmt.Errorf("数据盘名称格式无效")
	}
	return name, nil
}

// NormalizeLocalMountID validates the identifier used in generated mount
// paths and API route parameters.
func NormalizeLocalMountID(id string) (string, error) {
	id = strings.TrimSpace(id)
	if !localMountIDPattern.MatchString(id) {
		return "", fmt.Errorf("本地挂载 ID 格式无效")
	}
	return id, nil
}

// NormalizeVMName validates the identifier used in ~/.lima and limactl
// arguments. It must never be allowed to contain path separators.
func NormalizeVMName(name string) (string, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return "macnas", nil
	}
	if !vmNamePattern.MatchString(name) {
		return "", fmt.Errorf("虚拟机名称格式无效")
	}
	return name, nil
}

// NormalizeGuestTarget keeps a local mount target relative to /data. It is
// used at the API boundary and again while rendering VM configuration so a
// hand-edited config cannot escape the NAS data root.
func NormalizeGuestTarget(target string) (string, error) {
	target = strings.TrimSpace(target)
	if target == "" {
		return "", fmt.Errorf("挂载目标不能为空")
	}
	if len(target) > 512 || strings.Contains(target, `\`) || strings.IndexFunc(target, unicode.IsControl) >= 0 {
		return "", fmt.Errorf("挂载目标包含非法字符")
	}
	for _, part := range strings.Split(target, "/") {
		if part == ".." {
			return "", fmt.Errorf("挂载目标不能包含 ..")
		}
	}

	target = strings.TrimPrefix(target, "/data/")
	if target == "/data" || target == "data" {
		return "", fmt.Errorf("挂载目标不能是 /data 根目录")
	}
	target = strings.TrimPrefix(target, "/")
	if strings.HasPrefix(target, "data/") {
		target = strings.TrimPrefix(target, "data/")
	}
	clean := path.Clean(target)
	if clean == "." || clean == ".." || strings.HasPrefix(clean, "../") {
		return "", fmt.Errorf("挂载目标必须位于 /data 下")
	}
	return clean, nil
}

// ValidateLocalMount validates fields that are later embedded in the Lima
// template or the guest mount script. HostPath itself remains user-selectable;
// it is intentionally validated for shape here and for existence by storage.
func ValidateLocalMount(mount LocalMount) error {
	if _, err := NormalizeLocalMountID(mount.ID); err != nil {
		return err
	}
	if len(mount.Name) > 256 || strings.IndexFunc(mount.Name, unicode.IsControl) >= 0 {
		return fmt.Errorf("本地挂载名称包含非法字符")
	}
	if mount.HostPath == "" || !filepath.IsAbs(mount.HostPath) || len(mount.HostPath) > 4096 || strings.IndexFunc(mount.HostPath, unicode.IsControl) >= 0 {
		return fmt.Errorf("本地挂载路径无效")
	}
	_, err := NormalizeGuestTarget(mount.GuestTarget)
	return err
}

// EnsureSecrets makes sure a configuration has no known/default Samba
// password. It is intentionally separate from DefaultConfig because the
// latter cannot report a crypto/rand failure without changing its API.
func EnsureSecrets(cfg *Config) error {
	if cfg == nil {
		return errors.New("配置不能为空")
	}

	password := strings.TrimSpace(cfg.Samba.Password)
	if password != "" && password != legacySambaPassword {
		return ValidateSambaPassword(cfg.Samba.Password)
	}

	secret := make([]byte, 24)
	if _, err := rand.Read(secret); err != nil {
		return err
	}
	cfg.Samba.Password = hex.EncodeToString(secret)
	return nil
}

// ValidateSambaPassword is shared by config loading and password mutation so
// a hand-edited config cannot leave the Samba account with a value that the
// runtime later refuses to apply.
func ValidateSambaPassword(password string) error {
	if len([]byte(password)) < minSambaPasswordBytes {
		return fmt.Errorf("Samba 密码长度至少为 %d 个字节", minSambaPasswordBytes)
	}
	if len([]byte(password)) > maxSambaPasswordBytes || strings.IndexFunc(password, unicode.IsControl) >= 0 {
		return fmt.Errorf("Samba 密码长度不能超过 %d 个字节且不能包含控制字符", maxSambaPasswordBytes)
	}
	return nil
}

// NormalizeListenAddress accepts only literal IP addresses. Binding to
// loopback is the safe default; LAN exposure must be an explicit configuration
// choice such as 0.0.0.0 or a specific interface address.
func NormalizeListenAddress(address string) string {
	address = strings.TrimSpace(address)
	if address == "localhost" {
		return "127.0.0.1"
	}
	if net.ParseIP(address) != nil {
		return address
	}
	return "127.0.0.1"
}

func ConfigDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	dir := filepath.Join(home, ".macnas")
	if err := os.MkdirAll(dir, 0700); err != nil {
		return "", err
	}
	if err := os.Chmod(dir, 0700); err != nil {
		return "", err
	}
	return dir, nil
}

func ConfigFilePath() (string, error) {
	dir, err := ConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "config.yaml"), nil
}

func LoadConfig() (*Config, error) {
	path, err := ConfigFilePath()
	if err != nil {
		return DefaultConfig(), err
	}

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			cfg := DefaultConfig()
			if err := EnsureSecrets(cfg); err != nil {
				return cfg, fmt.Errorf("生成 Samba 初始密码失败: %w", err)
			}
			if err := SaveConfig(cfg); err != nil {
				return cfg, fmt.Errorf("保存初始配置失败: %w", err)
			}
			return cfg, nil
		}
		return DefaultConfig(), err
	}
	if err := os.Chmod(path, 0600); err != nil {
		return DefaultConfig(), fmt.Errorf("保护配置文件失败: %w", err)
	}

	cfg := DefaultConfig()
	if err := yaml.Unmarshal(data, cfg); err != nil {
		return DefaultConfig(), err
	}
	if cfg.Port < 1 || cfg.Port > 65535 {
		cfg.Port = 19808
	}
	cfg.ListenAddress = NormalizeListenAddress(cfg.ListenAddress)
	vmName, err := NormalizeVMName(cfg.VM.Name)
	if err != nil {
		return cfg, err
	}
	cfg.VM.Name = vmName
	if cfg.VM.CPUs <= 0 {
		cfg.VM.CPUs = 2
	}
	if cfg.VM.Memory <= 0 {
		cfg.VM.Memory = 4
	}
	if cfg.VM.DiskSize <= 0 {
		cfg.VM.DiskSize = 20
	}
	dataDiskName, err := NormalizeDataDiskName(cfg.VM.DataDiskName)
	if err != nil {
		return cfg, err
	}
	cfg.VM.DataDiskName = dataDiskName
	for i := range cfg.Storage.LocalMounts {
		target, err := NormalizeGuestTarget(cfg.Storage.LocalMounts[i].GuestTarget)
		if err != nil {
			return cfg, fmt.Errorf("本地挂载 %q 配置无效: %w", cfg.Storage.LocalMounts[i].ID, err)
		}
		cfg.Storage.LocalMounts[i].GuestTarget = target
		if err := ValidateLocalMount(cfg.Storage.LocalMounts[i]); err != nil {
			return cfg, fmt.Errorf("本地挂载 %q 配置无效: %w", cfg.Storage.LocalMounts[i].ID, err)
		}
	}
	if cfg.VM.ForwardedPorts == nil {
		cfg.VM.ForwardedPorts = append([]int(nil), DefaultConfig().VM.ForwardedPorts...)
	}
	cfg.VM.ForwardedPorts = NormalizeForwardedPorts(cfg.VM.ForwardedPorts)
	if cfg.Samba.Port < 1 || cfg.Samba.Port > 65535 {
		cfg.Samba.Port = 4455
	}
	if cfg.Samba.ShareName == "" {
		cfg.Samba.ShareName = "MacNAS"
	}
	if cfg.Samba.User == "" {
		cfg.Samba.User = "macnas"
	}
	needsSecret := strings.TrimSpace(cfg.Samba.Password) == "" || strings.TrimSpace(cfg.Samba.Password) == legacySambaPassword
	if err := EnsureSecrets(cfg); err != nil {
		return cfg, fmt.Errorf("生成 Samba 密码失败: %w", err)
	}
	if needsSecret {
		if err := SaveConfig(cfg); err != nil {
			return cfg, fmt.Errorf("保存安全配置失败: %w", err)
		}
	}
	return cfg, nil
}

var configMu sync.Mutex

func SaveConfig(cfg *Config) error {
	if cfg == nil {
		return errors.New("配置不能为空")
	}
	configMu.Lock()
	defer configMu.Unlock()
	return saveConfigLocked(cfg)
}

// Update applies a configuration mutation and persists it as one serialized
// transaction. The in-memory value is restored when validation, serialization,
// or the atomic file replacement fails, so concurrent domain managers cannot
// overwrite one another with a partially saved configuration.
func Update(cfg *Config, mutate func(*Config) error) error {
	if cfg == nil {
		return errors.New("配置不能为空")
	}
	if mutate == nil {
		return errors.New("配置更新函数不能为空")
	}

	configMu.Lock()
	defer configMu.Unlock()

	before, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}
	restore := func() error {
		var snapshot Config
		if err := yaml.Unmarshal(before, &snapshot); err != nil {
			return err
		}
		*cfg = snapshot
		return nil
	}

	if err := mutate(cfg); err != nil {
		if restoreErr := restore(); restoreErr != nil {
			return fmt.Errorf("配置更新失败: %v；回滚内存配置失败: %w", err, restoreErr)
		}
		return err
	}
	if err := saveConfigLocked(cfg); err != nil {
		if restoreErr := restore(); restoreErr != nil {
			return fmt.Errorf("保存配置失败: %v；回滚内存配置失败: %w", err, restoreErr)
		}
		return err
	}
	return nil
}

// Snapshot returns a deep, serialized copy of the configuration. Domain
// managers use it for read-heavy work so a concurrent Update cannot expose a
// partially mutated slice or nested value.
func Snapshot(cfg *Config) (*Config, error) {
	if cfg == nil {
		return nil, errors.New("配置不能为空")
	}
	configMu.Lock()
	defer configMu.Unlock()

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	var snapshot Config
	if err := yaml.Unmarshal(data, &snapshot); err != nil {
		return nil, err
	}
	return &snapshot, nil
}

func saveConfigLocked(cfg *Config) error {

	path, err := ConfigFilePath()
	if err != nil {
		return err
	}
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}

	tmpFile, err := os.CreateTemp(filepath.Dir(path), ".config.yaml-*")
	if err != nil {
		return err
	}
	tmpPath := tmpFile.Name()
	defer func() { _ = os.Remove(tmpPath) }()
	if err := tmpFile.Chmod(0600); err != nil {
		_ = tmpFile.Close()
		return err
	}
	if _, err := tmpFile.Write(data); err != nil {
		_ = tmpFile.Close()
		return err
	}
	if err := tmpFile.Sync(); err != nil {
		_ = tmpFile.Close()
		return err
	}
	if err := tmpFile.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return err
	}
	return os.Chmod(path, 0600)
}
